@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class Router ROUTER_COLOR
    Class Auth AUTH_COLOR
    Class Storage STORAGE_COLOR
    Class Logic LOGIC_COLOR
    Class Main #grey
    Class Commons AUTH_COLOR_T2
}

Class Frontend FRONTEND_COLOR
Class "<$documents>" as File ROUTER_COLOR_T1

Router -right[#green]> Auth
Router -[#green]> Logic
Auth -[#blue]-> Storage
Logic .down[#blue]-> Auth
Main -[#grey]-> Router
Main -[#grey]-> Auth
Main -[#grey]-> Storage
Main -up[#grey]-> Logic
Main -down[hidden]-> Commons
Logic -down[LOGIC_COLOR]-> Storage

Storage .right[STORAGE_COLOR].>File
Frontend ..> Router
@enduml
