@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include style.puml

Package " "<<Rectangle>>{
    Class Router ROUTER_COLOR
    Class Auth AUTH_COLOR
    Class Storage STORAGE_COLOR
    Class Logic LOGIC_COLOR
    Class Main #grey
    Class Commons AUTH_COLOR_T2
}

Class Frontend FRONTEND_COLOR
Class "<$documents>" as File ROUTER_COLOR_T1

Router -down[#green]-> Logic
Logic -left[LOGIC_COLOR]-> Auth
Logic -down[LOGIC_COLOR]-> Storage
Main -down[hidden]-> Commons

Storage .right[STORAGE_COLOR].>File
Frontend ..> Router
@enduml
