@startuml
!include ../style.puml
skinparam ArrowFontStyle plain

Participant ":LogicManager" as logic AUTH_COLOR
Participant ":AddressBookParser" as abp AUTH_COLOR
Participant ":EditCommandParser" as ecp AUTH_COLOR
Participant "command:EditCommand" as ec AUTH_COLOR

[-> logic : execute
activate logic
logic -> abp ++: parseCommand(commandText)
create ecp
abp -> ecp
abp -> ecp ++: parse(arguments)
create ec
ecp -> ec ++: index, editPersonDescriptor
ec --> ecp --
ecp --> abp --: command
abp --> logic --: command

@enduml
